FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libsndfile1 \
    ffmpeg \
    git \
    build-essential \
    espeak-ng \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    torch==2.3.0 torchaudio==2.3.0 torchvision==0.18.0

RUN pip install --no-cache-dir \
    audiosr \
    fastapi \
    uvicorn \
    python-multipart \
    soundfile \
    matplotlib \
    librosa \
    einops \
    ftfy \
    gradio \
    phonemizer \
    progressbar \
    torchlibrosa \
    transformers \
    timm

COPY app.py .

EXPOSE 8004

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8004", "--timeout-keep-alive", "1800"]